const CURRENT_USER_SET = "CURRENT_USER_SET";
const CURRENT_USER_DELETE = "CURRENT_USER_DELETE";
const SET_SESSION_ERROR = "SET_SESSION_ERROR";
const SET_CURRENT_USER_TOKEN = "SET_CURRENT_USER_TOKEN";
const CLEAR_SESSION_ERROR = "CLEAR_SESSION_ERROR";

export {
  CURRENT_USER_SET,
  CURRENT_USER_DELETE,
  SET_SESSION_ERROR,
  SET_CURRENT_USER_TOKEN,
  CLEAR_SESSION_ERROR
};
