const IS_FETCHING_PRODUCTS = "IS_FETCHING_PRODUCTS";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
const SET_PRODUCTS_PAGINATION = "SET_PRODUCTS_PAGINATION";
const NEXT_PRODUCT_PAGE = "NEXT_PRODUCT_PAGE";
const PREVIOUS_PRODUCT_PAGE = "PREVIOUS_PRODUCT_PAGE";

export {
  IS_FETCHING_PRODUCTS,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAILURE,
  SET_PRODUCTS_PAGINATION,
  NEXT_PRODUCT_PAGE,
  PREVIOUS_PRODUCT_PAGE
};
